name: Build and Release Windows Binary

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            # Adjust the path if go.sum is not in the root
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build Windows Binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o delete-maya-virus.exe
        env:
          CGO_ENABLED: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: delete-maya-virus-windows
          path: delete-maya-virus.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: delete-maya-virus-windows
          path: ./build-artifacts

      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./build-artifacts/delete-maya-virus.exe
