name: Build Windows Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"  # Enclosed in quotes

      - name: Install dependencies
        run: go mod tidy

      - name: Build Windows Binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o delete-maya-virus.exe
        env:
          CGO_ENABLED: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: delete-maya-virus-windows
          path: delete-maya-virus.exe